# binds
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind -r H resize-pane -L 3
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 3

# globals 
set -s escape-time 0

set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
set -g @vim_navigator_prefix_mapping_clear_screen ""

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:RGB"

set -g mouse off
set -g history-limit 10000
set -g base-index 0
setw -g pane-base-index 0

if-shell "uname | grep -q Linux" \
  "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'"

# status bar
set -g status on

set -g status-style "bg=default"
set -g status-left-length 40
set -g status-left "#[fg=#699469,bold]󰄛 tmux #[fg=#363646,bg=default]#[fg=#98BB6C,bg=#363646]#S#[fg=#363646,bg=default]"

set -g status-right-length 60
set -g status-right "#[fg=#363646,bg=default]#[fg=#949fb5,bold,bg=#363646]%a, %b %e#[fg=#363646,bg=default] #[fg=#8992a7]date "

set -g status-position top 
set -g status-justify centre 

setw -g window-status-current-style "bg=default"
setw -g window-status-current-format "#[fg=#363646,bg=default]#[fg=#c4b28a,bold,bg=#363646]#I #W#[fg=#363646,bg=default]"

setw -g window-status-style "fg=#727169,bold,bg=default"
setw -g window-status-format " #I #W "

# panes
set -g pane-border-style "fg=#d9a594"
set -g pane-active-border-style "fg=#716e61"

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
run '~/.tmux/plugins/tpm/tpm'
